/*
 * This source file was generated by the Gradle 'init' task
 */
package win.yakiimo;

import org.bukkit.plugin.java.JavaPlugin;

public class App extends JavaPlugin {
    @Override
    public void onEnable() {
        getLogger().info("プラグインが起動したよ！");
    }
}
